version: "3.9"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=edventures
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=edventures
      - DB_USER=devuser
      - DB_PASS=changeme
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
